### ISSUE TITLE
Toggle Button colors

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-showcase-demo#131]
The toggle buttons do not currently exist in material design 3's guideline, but inferring from other similar designs, the selected item should have a background color "primary container", and foreground color "on primary container".

From https://github.com/etn-ccis/blui-react-native-themes/issues/57

**Comment by ektaghag-eaton** [comment]
fixed here https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/134
