### ISSUE TITLE
InfoListItem icon colors

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-showcase-demo#137]
#### Describe the bug / expected behavior
Icons like these should be "on-surface-variant"
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/4d5cb969-08eb-4f1e-b963-09a6d43e2c20)

From https://github.com/etn-ccis/blui-react-native-themes/issues/57

**Comment by ektaghag-eaton** [comment]
This is fixed [here](https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/134)
