### ISSUE TITLE
Surface components should be styled properly to reflect the elevation change

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#138]
#### Describe the bug / expected behavior

In the kitchen sink, in `Surface` component, the `elevation` is passed in as a `style` prop
https://github.com/etn-ccis/blui-react-native-showcase-demo/blob/32185a28db4a95907da9187dd4fe9049a5266500/components/KitchenSink.tsx#L890

This caused all `Surface`s to render exactly the same.

#### Suggested fix

Adjust the implementation so that the surface is showcasing the style properly, according to [Surface's API documentation](https://callstack.github.io/react-native-paper/docs/components/Surface/).

**Comment by ektaghag-eaton** [comment]
Fixed https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/147
