### ISSUE TITLE
Avatar icon color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#152]
The avatar icon has different colors in the page body and in the header. The design matches closer to the one in the header.

![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/a6d40e1e-0c41-4664-97ce-daf826346779)

**Comment by ektaghag-eaton** [comment]
BLUI-5071

**Comment by joebochill** [comment]
Just need to pass the color prop to the Avatars in the body to match
