### ISSUE TITLE
Text Field background color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#153]
## Describe the bug / expected behavior
The background color of enabled text fields looks incorrect.

## Screenshots / Screen recording
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/a12221fa-7a0a-4c54-9b92-9a5d6fe6f19d)

Dark theme:
Enabled -- too bright, disabled -- too dark
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/db601b33-4278-4665-97d3-7cfdac75e24f)

## Suggested fix

In the design, an enabled text field takes a custom color: neutral-80 at 40% opacity for the light theme and 20% for the dark theme.

![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/6968059a-37ef-4811-983d-3aa36942b3f1)

In addition, a disabled text field should have a background color `disabled-container`, and everything on it should be `on-disabled-container`

**Comment by ektaghag-eaton** [comment]
BLUI-5072

**Comment by ektaghag-eaton** [comment]
https://github.com/etn-ccis/blui-react-native-showcase-demo/issues/157 is duplicate.

**Comment by huayunh** [comment]
#157 is not a duplicate issue and talks about a different problem
