### ISSUE TITLE
Text field's error messages not in the correct position

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#154]
# Describe the bug / expected behavior
Text field helper text / error messages are not placed in the horizontally correct position. 

# Screenshots / Screen recording

![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/7cd277d1-5173-4fe0-8991-6fbd3fe5fc4b)

# Suggested fix

There is a 16px left and right padding, as highlighted below:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/a98fa2a6-b654-467a-96bd-5335fa5e7e32)

# Anything else to add?
These helper texts are not directly visible from the component sticker sheet. To actually see them, you need to actually get a component instance and turn on the relevant options:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/b44f08c7-ad35-406f-b8e4-2acbfa1b44f4)

**Comment by ektaghag-eaton** [comment]
BLUI-5073
