### ISSUE TITLE
Banner avatar has a strange icon color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#155]
## Describe the bug / expected behavior

Why is this one so dark?
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/7032260c-3181-4ed2-9770-202720aa8906)

## Suggested fix

Either make it white ("on primary")
Or make the avatar tonal ("primary container" and "on primary container")

**Comment by ektaghag-eaton** [comment]
BLUI-5074
