### ISSUE TITLE
Toggle button color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#156]
## Describe the bug / expected behavior
Inactive buttons should not bear a blue tonal color.

## Screenshots / Screen recording
Dev:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/6cfab534-b845-4a2d-bed7-73c591e15cb4)

Design:
Design equivalent is called "segmented button", located with other buttons in the component sticker sheet:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/964f9818-77f9-4de9-90a7-7959d7f12de7)

Material Design 3's related documentation:
https://m3.material.io/components/segmented-buttons/guidelines

**Comment by ektaghag-eaton** [comment]
BLUI-5016
