### ISSUE TITLE
Text field user input color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#157]
#### Describe the bug / expected behavior

the text users type into the text field feels very dim in dark theme.
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/124b1196-83df-4c6e-b5ea-28edc30c748e)

#### Suggested fix

The correct color is `on-surface` for both light and dark theme.

**Comment by ektaghag-eaton** [comment]
BLUI-5075

**Comment by ektaghag-eaton** [comment]
In RNP 

For Flat input, text mode color is [onSurfaceVariant](https://github.com/callstack/react-native-paper/blob/726b98f371a84b302b553793679279d4c86555ff/src/components/TextInput/helpers.tsx#L331)

For outlined text mode color is [onSurface](https://github.com/callstack/react-native-paper/blob/726b98f371a84b302b553793679279d4c86555ff/src/components/TextInput/helpers.tsx#L334)

**Comment by ektaghag-eaton** [comment]
> In RNP
> 
> For Flat input, text mode color is [onSurfaceVariant](https://github.com/callstack/react-native-paper/blob/726b98f371a84b302b553793679279d4c86555ff/src/components/TextInput/helpers.tsx#L331)
> 
> For outlined text mode color is [onSurface](https://github.com/callstack/react-native-paper/blob/726b98f371a84b302b553793679279d4c86555ff/src/components/TextInput/helpers.tsx#L334)

Logged an issue under question category : https://github.com/callstack/react-native-paper/issues/4250
