### ISSUE TITLE
Dark theme error text field not showing its error state when not activated

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#158]
## Describe the bug / expected behavior
Error text fields, such as this "error dense outline text input", is not showing its error state properly. At least not when the text field is inactive.

![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/f9eb3ad7-a530-408c-a263-f263c23cb3b1)

## Suggested fix
Design:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/e7ca0e67-5782-4054-95ba-166eee993632)

## Anything else to add?
Surprisingly, they work fine in the light theme:

![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/a3b24886-869c-498e-9f7c-50027d997f85)

**Comment by surajeaton** [comment]
@huayunh We are maintaining a single state for handling all the errors. The screenshot in the issue has "Hel" (a valid input) in **Error Dense Outline Filled TextInput**, which is simultaneously changing the state of "Error Dense Outline TextInput" removing the error.

Please refer to the screen recording:

https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/120575281/aadec161-84ca-41cd-91ca-3b0ffa46e893

**Comment by huayunh** [comment]
Ooh, ok. Thanks for checking.
