### ISSUE TITLE
Dark theme contained error button text color 

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#159]
#### Describe the bug / expected behavior

The highlighted color looks blue ish. Expecting it to be `on-error`
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/d0e978d2-cc24-4263-abc8-7d9e63cf32df)

**Comment by ektaghag-eaton** [comment]
BLUI-5078

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/174 )
