### ISSUE TITLE
Elevated button wrong background color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#167]
#### Describe the bug / expected behavior

The background color of default "elevated" buttons is incorrect.

![image](https://github.com/etn-ccis/blui-react-native-themes/assets/8997218/ba68219a-fa8c-467b-be34-7a936cb167da)

![image](https://github.com/etn-ccis/blui-react-native-themes/assets/8997218/b28b3127-a978-44d5-85eb-9b66d75c6ec3)

#### Suggested fix

Expecting "surface container low". The button looks like "surface container lowest"

**Comment by ektaghag-eaton** [comment]
BLUI-5085
