### ISSUE TITLE
Filled Text Field Underline color

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-showcase-demo#172]
## Describe the bug / expected behavior

For "Filled"/ "Flat" styled text fields, their "active indicator"/"underline" color should be `on-surface-variant`. We are talking about this color:
![image](https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/8997218/c22d46f5-3fc8-4adb-9a37-33c1cf2cc8e6)

This is mandated by Material Design. https://m3.material.io/components/text-fields/specs

## Screenshots / Screen recording

See the screenshots in #153 -- the existing text field in dev seem to not have the correct underline color. Needs to be darker in light theme, and lighter in dark theme.

**Comment by ArshdeepSingh3-eaton** [comment]
Logged an issue under question category : [issue](https://github.com/callstack/react-native-paper/issues/4252)
